module Scenes.AllScenes exposing (..)

{-| This module is generated by Messenger, don't modify this.

This module records all the scenes.

@docs allScenes

-}


import Scenes.Home.Model as Home
import Messenger.Scene.Loader exposing (SceneStorage, sceneInit)
import Scenes.SceneSettings exposing (SceneInitMsg)


{-| allScenes
Add all the scenes here
-}
allScenes : List ( String, SceneStorage localstorage SceneInitMsg )
allScenes =
    [ ( "Home", sceneInit Home.concreteScene)
    ]

